#include "globals.h"
#include "notes.hpp"
#include <vector>

std::vector<Note> allNotes = {
    { NoteName::C, Accidental::Natural, 2 },
    { NoteName::C, Accidental::Sharp, 2 },
    { NoteName::C, Accidental::Flat, 2 },
    { NoteName::D, Accidental::Natural, 2 },
    { NoteName::D, Accidental::Sharp, 2 },
    { NoteName::D, Accidental::Flat, 2 },
    { NoteName::E, Accidental::Natural, 2 },
    { NoteName::E, Accidental::Sharp, 2 },
    { NoteName::E, Accidental::Flat, 2 },
    { NoteName::F, Accidental::Natural, 2 },
    { NoteName::F, Accidental::Sharp, 2 },
    { NoteName::F, Accidental::Flat, 2 },
    { NoteName::G, Accidental::Natural, 2 },
    { NoteName::G, Accidental::Sharp, 2 },
    { NoteName::G, Accidental::Flat, 2 },
    { NoteName::A, Accidental::Natural, 2 },
    { NoteName::A, Accidental::Sharp, 2 },
    { NoteName::A, Accidental::Flat, 2 },
    { NoteName::B, Accidental::Natural, 2 },
    { NoteName::B, Accidental::Sharp, 2 },
    { NoteName::B, Accidental::Flat, 2 },
    { NoteName::C, Accidental::Natural, 3 },
    { NoteName::C, Accidental::Sharp, 3 },
    { NoteName::C, Accidental::Flat, 3 },
    { NoteName::D, Accidental::Natural, 3 },
    { NoteName::D, Accidental::Sharp, 3 },
    { NoteName::D, Accidental::Flat, 3 },
    { NoteName::E, Accidental::Natural, 3 },
    { NoteName::E, Accidental::Sharp, 3 },
    { NoteName::E, Accidental::Flat, 3 },
    { NoteName::F, Accidental::Natural, 3 },
    { NoteName::F, Accidental::Sharp, 3 },
    { NoteName::F, Accidental::Flat, 3 },
    { NoteName::G, Accidental::Natural, 3 },
    { NoteName::G, Accidental::Sharp, 3 },
    { NoteName::G, Accidental::Flat, 3 },
    { NoteName::A, Accidental::Natural, 3 },
    { NoteName::A, Accidental::Sharp, 3 },
    { NoteName::A, Accidental::Flat, 3 },
    { NoteName::B, Accidental::Natural, 3 },
    { NoteName::B, Accidental::Sharp, 3 },
    { NoteName::B, Accidental::Flat, 3 },
    { NoteName::C, Accidental::Natural, 4 },
    { NoteName::C, Accidental::Sharp, 4 },
    { NoteName::C, Accidental::Flat, 4 },
    { NoteName::D, Accidental::Natural, 4 },
    { NoteName::D, Accidental::Sharp, 4 },
    { NoteName::D, Accidental::Flat, 4 },
    { NoteName::E, Accidental::Natural, 4 },
    { NoteName::E, Accidental::Sharp, 4 },
    { NoteName::E, Accidental::Flat, 4 },
    { NoteName::F, Accidental::Natural, 4 },
    { NoteName::F, Accidental::Sharp, 4 },
    { NoteName::F, Accidental::Flat, 4 },
    { NoteName::G, Accidental::Natural, 4 },
    { NoteName::G, Accidental::Sharp, 4 },
    { NoteName::G, Accidental::Flat, 4 },
    { NoteName::A, Accidental::Natural, 4 },
    { NoteName::A, Accidental::Sharp, 4 },
    { NoteName::A, Accidental::Flat, 4 },
    { NoteName::B, Accidental::Natural, 4 },
    { NoteName::B, Accidental::Sharp, 4 },
    { NoteName::B, Accidental::Flat, 4 },
    { NoteName::C, Accidental::Natural, 5 },
    { NoteName::C, Accidental::Sharp, 5 },
    { NoteName::C, Accidental::Flat, 5 },
    { NoteName::D, Accidental::Natural, 5 },
    { NoteName::D, Accidental::Sharp, 5 },
    { NoteName::D, Accidental::Flat, 5 },
    { NoteName::E, Accidental::Natural, 5 },
    { NoteName::E, Accidental::Sharp, 5 },
    { NoteName::E, Accidental::Flat, 5 },
    { NoteName::F, Accidental::Natural, 5 },
    { NoteName::F, Accidental::Sharp, 5 },
    { NoteName::F, Accidental::Flat, 5 },
    { NoteName::G, Accidental::Natural, 5 },
    { NoteName::G, Accidental::Sharp, 5 },
    { NoteName::G, Accidental::Flat, 5 },
    { NoteName::A, Accidental::Natural, 5 },
    { NoteName::A, Accidental::Sharp, 5 },
    { NoteName::A, Accidental::Flat, 5 },
    { NoteName::B, Accidental::Natural, 5 },
    { NoteName::B, Accidental::Sharp, 5 },
    { NoteName::B, Accidental::Flat, 5 }
};
Note CURRENTNOTE = {NoteName::C, Accidental::Natural, 0};
std::atomic<bool> RUNNINGPROGRAM = true;
std::atomic<bool> SHARPS = true;
std::atomic<double> VOLUMETHRESHOLD = 1.0;